name: Linters

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  rubocop:
    name: RuboCop Action
    runs-on: ubuntu-latest
    timeout-minutes: 2
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - uses: actions/cache@v1.1.2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Bundle
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run Rubocop
        run: bin/rubocop
  shell_linter:
    name: Shell Lint Action
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@master
      - name: Run Shell Linter
        uses: azohra/shell-linter@v0.1.0
